### ISSUE TITLE
Problems with addon-info.txt?

### ISSUE THREAD

**Issue by decibel** [MarcWeber/vim-addon-manager#170]
Trying to use https://github.com/LucHermitte/local_vimrc. If I simply include that in ActivateAddons:

ActivateAddons local_vimrc "sensible surround git.zip fugitive

It blows up with missing lh-blah functions. Instead I have to do

ActivateAddons lh-vim-lib local_vimrc sensible surround git.zip fugitive

My understanding is that I shouldn't need to specify lh-vim-lib, and https://github.com/LucHermitte/local_vimrc/blob/master/addon-info.txt looks reasonable to me. Is this a bug in VAM?

**Comment by ZyX-I** [comment]
@decibel No, it is not. `addon-info.txt` is *not* a valid name, one needs to use `addon-info.json`.
