### ISSUE TITLE
vim does not see helptags for addons

### ISSUE THREAD

**Issue by cizmazia** [MarcWeber/vim-addon-manager#172]
I followed the [recommended setup][1], however Vim does not see **helptags** for addons. E.g. when pressing Shift_K on a tag in `vimwiki.txt`, I get an error: "No manual entry for vimwiki-text-objects"

Any pointers appreciated.

[1]: https://github.com/MarcWeber/vim-addon-manager/blob/master/doc/vim-addon-manager-getting-started.txt#L120

**Comment by ZyX-I** [comment]
`K` is not supposed to work in help at all, unless you have remapped it.

**Comment by cizmazia** [comment]
Thanks for you response. `Ctrl+]` works.
