### ISSUE TITLE
Win64: The filename, directory name, or volume label syntax is incorrect. By a last slash in path.

### ISSUE THREAD

**Issue by jacula** [MarcWeber/vim-addon-manager#177]
---

**NOGUI VIM**

:UpdateAddons

The filename, directory name, or volume label syntax is incorrect.

shell returned 1

Press ENTER or type command to continue

Updating C:\Users\ego\vimfiles\vim-addons/vim-pi failed. The :AddonInfo command may tell you about a new upstream source. If in doubt move the plugin directory somewhere else, install it from scratch and check the differences
The following scm keys are the same as vim.org ones: vim-gradle, caw.
These plugins should either be renamed or put into scmnr dictionary.
Update all loaded plugins?
[Y]es, (N)o:

---

**GUI VIM**

:UpdateAddons

C:\WINDOWS\system32\cmd.exe /c (^"cd 'C:/Users/ego/vimfiles/vim-addons/vim-pi' ^&^& git pull^")
The filename, directory name, or volume label syntax is incorrect.
shell returned 1
Hit any key to close this window...

**Comment by MarcWeber** [comment]
I don't care much about windows right now. You can see the cd '... command. Try opening the shell (win-r -> cmd) then copy paste that line. Do you still get an error? Remove the ^ signs first.

**Comment by jacula** [comment]
I thank you very much for your attention. I'm sorry to have presented a problem that concerns more windows with vim that vim with vam. However, the problem is not the cd command, but the expansion of the path to the directory, as you can see:

Updating C:\Users\ego\vimfiles\**vim-addons/vim-pi** failed

Thanks :-)

**Comment by MarcWeber** [comment]
vam.mawercer.de -> Download one plugin, compare that configuration with yours? "The expansion" is done by a function with a default implementation in VAM.

    let s:c.plugin_dir_by_name   = get(s:c, 'plugin_dir_by_name',   'vam#DefaultPluginDirFromName')

    fun! vam#DefaultPluginDirFromName(name) abort
      " this function maps addon names to their storage location. \/: are replaced
      " by - (See name rewriting)
      let dirs = [s:c.plugin_root_dir] + s:c.additional_addon_dirs
      let name = substitute(a:name, '[\\/:]\+', '-', 'g')
      let existing = filter(copy(dirs), "isdirectory(v:val.'/'.".string(name).')')
      return (empty(existing) ? dirs[0] : existing[0]).'/'.name
    endfun


Thus also look at plugin_root_dir configuration setting?

**Comment by jacula** [comment]
I thank you. I solved the problem by my vimrc.
I already checked the code in vam.vim; it works perfectly in windows.
Instead I solved my problem commenting out:
"set shellslash
"set shellquote=\"

in my _vimrc.

I apologize for making you waste time

Thanks :-)

**Comment by MarcWeber** [comment]
So there are 3 solutions 1) be done 2) fix VAM (by setting/resetting values) 3) by adding an assertion. If somebody else runs into this issue or if you have conflicts with other plugins we can discuss the solution
