### ISSUE TITLE
Why I get the 

### ISSUE THREAD

**Issue by woshichuanqilz** [MarcWeber/vim-addon-manager#179]
**The following scm keys are the same as vim.org ones**

![1219210731.png](http://7xpvdr.com1.z0.glb.clouddn.com/1219210731.png)

**I put the `vim-snippet` here.** 
![1219213153.png](http://7xpvdr.com1.z0.glb.clouddn.com/1219213153.png)

**And My `vimrc` file:**
![1219213256.png](http://7xpvdr.com1.z0.glb.clouddn.com/1219213256.png)

**Comment by MarcWeber** [comment]
See vim-pi commits - vim-gradle -> 2 versions -> I chose the www.vim.org by default, the other can be accessed by vim-gradle@tfnico, caw -> github url was added, conflict between "same" repo. resolved by associating with script id.
