### ISSUE TITLE
Problem with vam#install#Install

### ISSUE THREAD

**Issue by j-degreef** [MarcWeber/vim-addon-manager#180]
Hi,

I'm trying to install vim-airline-themes using vam#install#Install.
vim-airline-themes is not in the vi-pi database so I created a .json file with the infos to install it.
Here's the content of my *-addon-info.json:
{
  "name" : "vim-airline-themes",
  "version" : "undefined",
  "repository" : {"type": "git", "url": "https://github.com/vim-airline/vim-airline/vim-airline-themes.git"},
  "dependencies" : {},
  "description" : "Themes for vim-airline"
}
I call it from .vimrc with :
call vam#install#Install(["/home/jdegreef/vim-airline-themes-addon-info.json"], {}

It fails with these messages in the log : 

Mon 20 Feb 2017 03:51:07 AM CET
pool item https://github.com/vim-airline/vim-airline/vim-airline-themes.git: should not be using http:// for consistency. If you need http see MyGitCheckout example
pool item https://github.com/vim-airline/vim-airline/vim-airline-themes.git: github urls also work without .git suffix. Drop if for copy paste and consistency reasons
No repository location info known for plugin /home/jdegreef/vim-airline-themes-addon-info.json.

I've tried removing .git and https:// without succes, it still fails saying No repository location info known for plugin /home/jdegreef/vim-airline-themes-addon-info.json.

I've spend hours reading the documentation trying to solve this without success.
Any help would be appreciated.
Thanks in advance,
Jerome

**Comment by MarcWeber** [comment]
https://github.com/MarcWeber/vim-addon-manager -> README.md -> PLUGIN_NAME What is a plugin -> you can install by using such name which gets rewritten correctly:  "github:user/repo". Thus grepping for github would have found the most simple solution. vim-pi does have a .vim file containing additional name/sources. We could add this plugin there then the community will find it.

I just forgot about your usage whether it ought work or not. If it is an issue I'll look into it.I recall that having dependencies in a json file pointing to repositories this way should work.

**Comment by j-degreef** [comment]
Hi,

Thanks for your quick reply.

 "github:user/repo" works except that it is not rewritten correctly : 
Unless I miss something,  "github:vim-airline/vim-airline-themes" is rewritten "github-vim-airline-vim-airline-themes" and then vim-airline doesn't find it's themes because it expects them in the "vim-airline-themes directory".

Adding vim-airline-themes to vim-pi would be a good solution.
I've tried with this line in "scmsources.vim" and it works :
" Jérôme De Greef
let scm['vim-airline-themes'] = {'type': 'git', 'url': 'git://github.com/vim-airline/vim-airline-themes'}
Btw, some addons are referenced by a number in this file, where does it come from ?

About "my usage" it's not a problem if it doesn't work but it's a bit frustrating to try to make something work as in the documentation and then learn by the developer that it actually doesn't work.

Anyway, thanks for your work.
Best regards,
Jérôme

**Comment by ZyX-I** [comment]
@j-degreef If I am not mistaking, it should be possible to place airline themes *anywhere* in &runtimepath, so you there is an error somewhere else, `github-vim-airline-vim-airline-themes` name should work like any other directory name.

Number is a number from vim.org.

**Comment by j-degreef** [comment]
@ZyX-I My bad, I forgot that vam#install#Install only install the addon. When I activate it it works ok :)
Thanks for helping.
